// <auto-generated />
namespace FIT5032Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class itemdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202010120112348_item-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
